# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: fix-byte-order-marker
    -   id: check-case-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-xml
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: destroyed-symlinks
    -   id: mixed-line-ending
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.30.0
    hooks:
    -   id: eslint
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
        -   'eslint-plugin-node@^11.1.0'
        -   'eslint-plugin-promise@^5.1.0'
-   repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
    -   id: markdownlint
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
    -   id: detect-secrets
        exclude: package.lock.json
